/**
 * API types + fetch client.
 *
 * Every type here was generated by hand from the ACTUAL payloads of the FinOps
 * API running with DATA_SOURCE=demo (see services/api/app/main.py). Where the
 * BigQuery path returns a narrower shape than demo, the extra fields are marked
 * optional so both conform. The client renders these; it never recomputes them.
 */

import type { Scope } from "./scope";

const BASE = (import.meta.env.VITE_API_BASE ?? "").replace(/\/$/, "");

// --------------------------------------------------------------------------
// Meta
// --------------------------------------------------------------------------

export interface SourceDescription {
  source: string;
  live: boolean;
  rows?: number;
  focus_version: string;
  conformant?: boolean;
  period_start?: string;
  period_end?: string;
  note?: string;
  // BigQuery path
  table?: string;
  max_bytes_billed?: number;
}

export interface Meta {
  organisation: string;
  environment: string;
  source: SourceDescription;
  ai_enabled: boolean;
  models: { reasoning: string; routing: string };
  focus_version: string;
  personas: string[];
  domains: string[];
  groupable: string[];
}

export interface Dimensions {
  clouds: string[];
  applications: string[];
  business_units: string[];
  environments: string[];
}

// --------------------------------------------------------------------------
// Executive KPIs -- mirrors finops_core.kpi.ExecutiveKPIs (demo path).
// The BigQuery path omits several fields, hence the optionals.
// --------------------------------------------------------------------------

export interface Kpis {
  total_spend: number;
  mom_pct: number | null;
  yoy_pct?: number | null;
  run_rate?: number | null;
  esr_pct: number | null;
  coverage_pct?: number | null;
  utilization_pct: number | null;
  commitment_waste: number;
  cost_of_waste?: number;
  waste_pct?: number | null;
  allocation_coverage_pct: number | null;
  chargeback_readiness: string;
  baseline_drift_pct?: number | null;
  // BigQuery path only
  period_start?: string;
  period_end?: string;
}

// --------------------------------------------------------------------------
// Spend
// --------------------------------------------------------------------------

export interface MonthlyRow {
  period: string;
  cost: number;
}
export interface MonthlyResponse {
  rows: MonthlyRow[];
}

/** Rows carry a DYNAMIC dimension column key (e.g. ProviderName). `column`
 *  names it. When the scope is empty `column` is absent. */
export interface SpendByRow {
  period: string;
  cost: number;
  [column: string]: string | number;
}
export interface SpendByResponse {
  dimension: string;
  column?: string;
  rows: SpendByRow[];
}

// --------------------------------------------------------------------------
// Forecast
// --------------------------------------------------------------------------

export interface ForecastHistoryRow {
  period: string;
  cost: number;
}
export interface ForecastRow {
  period: string;
  cost: number;
  lo80: number;
  hi80: number;
  lo95: number;
  hi95: number;
  cost_with_cliffs?: number;
}
export interface ForecastAccuracy {
  mape: number | null;
  wape: number | null;
  smape: number | null;
  folds: number | null;
}
export interface ForecastResponse {
  method: string;
  maturity: string;
  accuracy: ForecastAccuracy;
  notes: string[];
  history: ForecastHistoryRow[];
  forecast: ForecastRow[];
  cliff_months: string[];
  extra_from_cliffs_usd: number;
}

// --------------------------------------------------------------------------
// Optimize
// --------------------------------------------------------------------------

export interface OpportunityRow {
  lever_id: string;
  lever_name: string;
  category: string;
  cloud: string;
  scope: string;
  monthly_savings: number;
  annual_savings: number;
  effort: string;
  risk: string;
  time_to_value: string;
  confidence: number;
  resource_count: number;
}
export interface OpportunitiesResponse {
  count: number;
  total_annual_savings: number;
  rows: OpportunityRow[];
}

export interface LeverRow {
  id: string;
  name: string;
  category: string;
  clouds: string;
  savings_low: number;
  savings_high: number;
  effort: string;
  risk: string;
  time_to_value: string;
  prerequisites: string;
  detection: string;
  source_url: string;
}
export interface LeversResponse {
  count: number;
  rows: LeverRow[];
}

// --------------------------------------------------------------------------
// Anomalies -- rows carry a dynamic dimension column key.
// --------------------------------------------------------------------------

export interface AnomalyRow {
  period: string;
  cost: number;
  expected: number;
  residual: number;
  score: number;
  is_anomaly: boolean;
  severity: string;
  deviation_pct: number;
  method: string;
  [column: string]: string | number | boolean;
}
export interface AnomaliesResponse {
  dimension: string;
  count?: number;
  rows: AnomalyRow[];
}

// --------------------------------------------------------------------------
// Allocation -- rows carry a dynamic dimension column key.
// --------------------------------------------------------------------------

export interface AllocationRow {
  direct_cost: number;
  shared_cost: number;
  untagged_cost: number;
  total_cost: number;
  pct_of_total: number;
  shared_pct: number;
  [column: string]: string | number;
}
export interface AllocationResponse {
  dimension?: string;
  method?: string;
  rows: AllocationRow[];
}

export const ALLOCATION_METHODS = [
  "direct",
  "even_split",
  "proportional",
  "fixed_percentage",
  "usage_driver",
] as const;
export type AllocationMethod = (typeof ALLOCATION_METHODS)[number];

// --------------------------------------------------------------------------
// Governance
// --------------------------------------------------------------------------

export interface CoverageRow {
  tag_key: string;
  coverage_pct: number;
  unallocated_cost: number;
  status: string;
}
export interface CoverageResponse {
  rows: CoverageRow[];
}

// --------------------------------------------------------------------------
// Agent team
// --------------------------------------------------------------------------

export interface AgentToolCard {
  name: string;
  summary: string;
}
export interface AgentCard {
  name: string;
  domain: string;
  description: string;
  model: string;
  tools: AgentToolCard[];
}
export interface AgentTeamResponse {
  enabled: boolean;
  agents: AgentCard[];
}

// --------------------------------------------------------------------------
// Fetch plumbing
// --------------------------------------------------------------------------

export class ApiError extends Error {
  status: number;
  constructor(status: number, message: string) {
    super(message);
    this.status = status;
    this.name = "ApiError";
  }
}

/** Append the shared scope to a URLSearchParams. Arrays repeat the key, which
 *  is exactly what FastAPI's `List[str] = Query(None)` expects. */
export function scopeToParams(scope: Scope, extra?: Record<string, string>): URLSearchParams {
  const p = new URLSearchParams();
  if (scope.start) p.set("start", scope.start);
  if (scope.end) p.set("end", scope.end);
  for (const c of scope.clouds) p.append("clouds", c);
  for (const a of scope.applications) p.append("applications", a);
  for (const b of scope.business_units) p.append("business_units", b);
  for (const e of scope.environments) p.append("environments", e);
  if (extra) for (const [k, v] of Object.entries(extra)) p.set(k, v);
  return p;
}

async function getJson<T>(path: string, params?: URLSearchParams, signal?: AbortSignal): Promise<T> {
  const qs = params && [...params].length ? `?${params.toString()}` : "";
  const res = await fetch(`${BASE}${path}${qs}`, { signal });
  if (!res.ok) {
    let detail = res.statusText;
    try {
      const body = await res.json();
      detail = body?.detail ?? detail;
    } catch {
      /* keep statusText */
    }
    throw new ApiError(res.status, detail);
  }
  return (await res.json()) as T;
}

// --------------------------------------------------------------------------
// Endpoints
// --------------------------------------------------------------------------

export const api = {
  meta: (signal?: AbortSignal) => getJson<Meta>("/api/meta", undefined, signal),
  dimensions: (signal?: AbortSignal) => getJson<Dimensions>("/api/dimensions", undefined, signal),

  kpis: (scope: Scope, signal?: AbortSignal) =>
    getJson<Kpis>("/api/kpis", scopeToParams(scope), signal),

  spendMonthly: (scope: Scope, signal?: AbortSignal) =>
    getJson<MonthlyResponse>("/api/spend/monthly", scopeToParams(scope), signal),

  spendBy: (scope: Scope, dimension: string, signal?: AbortSignal) =>
    getJson<SpendByResponse>("/api/spend/by", scopeToParams(scope, { dimension }), signal),

  forecast: (scope: Scope, horizon: number, signal?: AbortSignal) =>
    getJson<ForecastResponse>(
      "/api/forecast",
      scopeToParams(scope, { horizon: String(horizon), include_cliffs: "true" }),
      signal,
    ),

  opportunities: (
    scope: Scope,
    opts: { min_annual_savings?: number; category?: string },
    signal?: AbortSignal,
  ) => {
    const extra: Record<string, string> = {};
    if (opts.min_annual_savings) extra.min_annual_savings = String(opts.min_annual_savings);
    if (opts.category) extra.category = opts.category;
    return getJson<OpportunitiesResponse>(
      "/api/optimize/opportunities",
      scopeToParams(scope, extra),
      signal,
    );
  },

  levers: (signal?: AbortSignal) => getJson<LeversResponse>("/api/optimize/levers", undefined, signal),

  anomalies: (scope: Scope, dimension: string, signal?: AbortSignal) =>
    getJson<AnomaliesResponse>("/api/anomalies", scopeToParams(scope, { dimension }), signal),

  allocation: (scope: Scope, dimension: string, method: string, signal?: AbortSignal) =>
    getJson<AllocationResponse>(
      "/api/allocation",
      scopeToParams(scope, { dimension, method }),
      signal,
    ),

  coverage: (scope: Scope, signal?: AbortSignal) =>
    getJson<CoverageResponse>("/api/governance/coverage", scopeToParams(scope), signal),

  agentTeam: (signal?: AbortSignal) =>
    getJson<AgentTeamResponse>("/api/agent/team", undefined, signal),
};

export const API_BASE = BASE;
